### ISSUE TITLE
Omeka has encountered an error. 

### ISSUE THREAD

**Issue by CathyHajo** [Daniel-KM/CuratorMonitor#1]
I entered monitor data for one item and when I saved it I got the error message below:
http://ja20c.njdigitalhistory.org/admin/items/edit/19

Omeka has encountered an error

Zend_Http_Client_Exception

```
Passed parameter is not a valid HTTP URI.
```

exception 'Zend_Http_Client_Exception' with message 'Passed parameter is not a valid HTTP URI.' in /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Http/Client.php:312
Stack trace:
#0 /home1/njdigita/public_html/ja20c/omeka-2.1.4/plugins/Scripto/libraries/Scripto/Service/MediaWiki.php(113): Zend_Http_Client->setUri(NULL)
#1 /home1/njdigita/public_html/ja20c/omeka-2.1.4/plugins/Scripto/libraries/Scripto.php(77): Scripto_Service_MediaWiki->__construct(NULL, true)
#2 /home1/njdigita/public_html/ja20c/omeka-2.1.4/plugins/Scripto/ScriptoPlugin.php(406): Scripto->__construct(Object(ScriptoAdapterOmeka), Array)
#3 /home1/njdigita/public_html/ja20c/omeka-2.1.4/plugins/Scripto/ScriptoPlugin.php(322): ScriptoPlugin::getScripto()
#4 /home1/njdigita/public_html/ja20c/omeka-2.1.4/plugins/Scripto/ScriptoPlugin.php(289): ScriptoPlugin->_appendToItemsShow()
#5 [internal function]: ScriptoPlugin->hookAdminItemsShow(Array)
#6 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Omeka/Plugin/Broker.php(157): call_user_func(Array, Array)
#7 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/globals.php(188): Omeka_Plugin_Broker->callHook('admin_items_sho...', Array)
#8 /home1/njdigita/public_html/ja20c/omeka-2.1.4/admin/themes/default/items/show.php(23): fire_plugin_hook('admin_items_sho...', Array)
#9 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Omeka/View.php(117): include('/home1/njdigita...')
#10 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/home1/njdigita...')
#11 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(905): Zend_View_Abstract->render('items/show.php')
#12 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(926): Zend_Controller_Action_Helper_ViewRenderer->renderScript('items/show.php', NULL)
#13 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(965): Zend_Controller_Action_Helper_ViewRenderer->render()
#14 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#15 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#17 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#18 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#19 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Zend/Application.php(382): Zend_Application_Bootstrap_Bootstrap->run()
#20 /home1/njdigita/public_html/ja20c/omeka-2.1.4/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#21 /home1/njdigita/public_html/ja20c/omeka-2.1.4/admin/index.php(28): Omeka_Application->run()
#22 {main}

**Comment by Daniel-KM** [comment]
Hi,

This is not related to this plugin, but to the Scripto one: when HistoryLog and CurationMonitor are disabled, the bug still exists.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Daniel-KM** [comment]
Hi,
