### ISSUE TITLE
Get metadata for record not working for Monitor elements

### ISSUE THREAD

**Issue by adehner** [Daniel-KM/CuratorMonitor#2]
When I use the function below, I get this error:
Omeka_Record_Exception
There is no "Monitor", "Editor's Notes" element

echo metadata('item',array('Monitor',"Editor's Notes"));

The database shows the "Editor's Notes" element belonging to the "Monitor" element set, so I'm not sure why this is happening. Any ideas?

**Comment by Daniel-KM** [comment]
Hi,

In fact, there is a true apostrophe "`’`", not a single quote "`'`", as recommended in UTF-8 format.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
